import { v2 as cloudinary } from 'cloudinary';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// CONFIG
const CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const API_KEY = process.env.CLOUDINARY_API_KEY;
const API_SECRET = process.env.CLOUDINARY_API_SECRET;

if (!CLOUD_NAME || !API_KEY || !API_SECRET) {
    console.error('❌ Missing Cloudinary credentials.');
    console.error('Please create a .env file in the root directory with:');
    console.error('CLOUDINARY_CLOUD_NAME=your_cloud_name');
    console.error('CLOUDINARY_API_KEY=your_api_key');
    console.error('CLOUDINARY_API_SECRET=your_api_secret');
    process.exit(1);
}

// Configure Cloudinary
cloudinary.config({
    cloud_name: CLOUD_NAME,
    api_key: API_KEY,
    api_secret: API_SECRET,
    secure: true,
});

const VIDEOS_DIR = path.join(__dirname, '../public/Videos');

async function uploadVideos() {
    if (!fs.existsSync(VIDEOS_DIR)) {
        console.error(`❌ Videos directory not found at ${VIDEOS_DIR}`);
        return;
    }

    const files = fs.readdirSync(VIDEOS_DIR).filter(file => {
        const ext = path.extname(file).toLowerCase();
        return ['.mp4', '.mov', '.webm'].includes(ext);
    });

    console.log(`🎬 Found ${files.length} videos to upload from ${VIDEOS_DIR}...`);

    for (const file of files) {
        const filePath = path.join(VIDEOS_DIR, file);

        // We upload to a folder 'Videos' in Cloudinary to match the local path structure
        // so that /Videos/filename.mp4 becomes <CDN_URL>/Videos/filename.mp4

        console.log(`Uploading ${file}...`);
        try {
            await cloudinary.uploader.upload(filePath, {
                resource_type: 'video',
                folder: "Videos",      // This puts it in a 'Videos' folder in Cloudinary
                use_filename: true,    // Use the original filename
                unique_filename: false,// Don't append random characters
                overwrite: true,       // Overwrite if exists
            });
            console.log(`✅ Uploaded ${file}`);
        } catch (error) {
            console.error(`❌ Failed to upload ${file}:`, error.message);
        }
    }

    console.log('\n🎉 Upload Complete!');

    const cdnUrl = `https://res.cloudinary.com/${CLOUD_NAME}/video/upload`;
    const envPath = path.join(__dirname, '../.env');

    // Append or Update VITE_CDN_URL in .env
    let envContent = fs.existsSync(envPath) ? fs.readFileSync(envPath, 'utf8') : '';
    if (!envContent.includes('VITE_CDN_URL=')) {
        fs.appendFileSync(envPath, `\n\n# Auto-generated by upload script\nVITE_CDN_URL=${cdnUrl}`);
        console.log(`✅ Added VITE_CDN_URL to .env`);
    } else {
        console.log(`ℹ️ VITE_CDN_URL already exists in .env, please verify it matches: ${cdnUrl}`);
    }

    console.log('==========================================');
    console.log('CDN Configuration Ready!');
    console.log(`URL: ${cdnUrl}`);
    console.log('IMPORTANT: Restart your dev server for changes to take effect.');
    console.log('==========================================');
}

uploadVideos();
